
parameters:
  _param:
    salt_control_trusty_image: http://apt.tcpcloud.eu/images/ubuntu-14-04-x64-201612140957.qcow2
    salt_control_xenial_image: http://apt.tcpcloud.eu/images/ubuntu-16-04-x64-201612140953.qcow2
  linux:
    network:
      host:
        cfg01:
          address: ${_param:infra_config_address}
          names:
          - cfg01
          - cfg01.${_param:cluster_domain}
        cfg:
          address: ${_param:infra_config_address}
          names:
          - ${_param:infra_config_hostname}
          - ${_param:infra_config_hostname}.${_param:cluster_domain}
        kvm01:
          address: ${_param:infra_compute_node01_address}
          names:
          - ${_param:infra_compute_node01_hostname}
          - ${_param:infra_compute_node01_hostname}.${_param:cluster_domain}
        kvm02:
          address: ${_param:infra_compute_node02_address}
          names:
          - ${_param:infra_compute_node02_hostname}
          - ${_param:infra_compute_node02_hostname}.${_param:cluster_domain}
        kvm03:
          address: ${_param:infra_compute_node03_address}
          names:
          - ${_param:infra_compute_node03_hostname}
          - ${_param:infra_compute_node03_hostname}.${_param:cluster_domain}
